### ISSUE TITLE
How about the time-consuming?

### ISSUE THREAD

**Issue by JiuqingDong** [xiaomabufei/CAT#2]
Hi, thank you for your code!
I would like to know how many hours did you spend on the whole train process? (if 8 GPUs are available.)
looking forward to your reply.

**Comment by xiaomabufei** [comment]
We use 8 3090 and set the batch size as 3 images/per gpu, total 24 images/per batch. Total training time (containing Task 1,2,3,4 and  evaluation after per epoch) is no more than 48 hours for OWOD split.

**Comment by JiuqingDong** [comment]
Thank you for your reply! I will train it later.
