### ISSUE TITLE
Question about SAM

### ISSUE THREAD

**Issue by harrylin-hyl** [xiaomabufei/CAT#4]
I found the IOU you calculated in the following code is not the iou value but the iou index.
Is that normal?  

![image](https://user-images.githubusercontent.com/26209785/227467622-9c67b02a-141d-48c5-abfc-bb876b64c33d.png)

**Comment by xiaomabufei** [comment]
Thanks for the heads up, my group member uploaded the wrong version of the code and we have made the changes.

**Comment by xiaomabufei** [comment]
I'm on a business trip at the moment, I'll re-upload the latest version when I get back. Please wait for a moment.

**Comment by harrylin-hyl** [comment]
Ok, thanks for your timely reply and upload!
